name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Master
        uses: actions/checkout@v1
      - name: Use Node
        uses: actions/setup-node@master
        with:
          node-version: '13.x'
      - name: Install Dependencies using Yarn
        run: yarn install
      - name: Build
        run: yarn build
      - name: Test
        run: yarn test
      - name: Publish Canary
        env: # Or as an environment variable
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
        run: |
            if [ "${{github.repository}}" == "Urigo/merge-graphql-schemas" ] && [ "${{ secrets.NODE_AUTH_TOKEN }}" != "" ]
            then
                echo "//registry.npmjs.org/:_authToken=${{ secrets.NODE_AUTH_TOKEN }}" > .npmrc
                npm run ci:release:canary
            else    
                echo "Fork PR: ${{github.repository}}"
                echo "Skipping canary publish due to a fork/PR..."
            fi
